### PR TITLE
Fixed duplicate react types issue 

### LINKED ISSUE #96: Duplicate identifier 'LibraryManagedAttributes'.
**Version: 1.2.1' or '1.2.0'**

I got this error 'Duplicate identifier 'LibraryManagedAttributes'. when I run the application after installing 1.2.1 package or 1.2.0 package. 

> C:/...web/node_modules/@react-google-maps/api/node_modules/@types/react/index.d.ts
> (2777,14): Duplicate identifier 'LibraryManagedAttributes'.

seems like there is an issue with type/react version issue. How do I solve this?

Similiar issue?: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33822

- OS: Windows
- Node: v10.15.1
- "react": "^16.8.4",
- "react-bootstrap": "^1.0.0-beta.6",
- "react-dom": "^16.8.4",
- "react-router": "^5.0.0",
- "react-router-dom": "^5.0.0",

### PR DESCRIPTION
**Pull request by uriklar**
Fixes #96

### CODE REVIEW

**Comment by FredyC** [comment]
This is very tricky and I fighting with it every day. It's an annoying issue with Yarn. Anytime you update `@types/react`, other packages relying on it (even with `*` as version) will keep the old version. And that creates duplicates. The only cure I found so far is manually to edit `yarn.lock` and remove all occurrences and re-run.

However, in your case, your packages are requiring fixed types package version which makes it even worse.

I would recommend switching to Yarn workspaces which are [supported with Lerna](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces) which leads to a single `yarn.lock` and it's much easier to tackle this problem there.

**Comment by uriklar** [comment]
I removed the @types packages from being peerDependencies. I think this should resolve the issue. Deleting yarn.lock and rerunning currently fixes the issue for me

**Comment by FredyC** [comment]
Ok, but still, Yarn workspaces are much better. It's also easier for contributors as they don't need to bother with Lerna at all and just `yarn install` in a root.

**Comment by uriklar** [comment]
I'll check it out. Personally, i'd get rid of lerna altogether and have just one main package

**Pull request closed without merging**
