### PR TITLE
Update to React 18

### PR DESCRIPTION
**Pull request by JustFly1984**
# Please explain PR reason

### CODE REVIEW

**Comment by marduzca** [comment]
@JustFly1984 
To help you test it I have just pulled it and tried running both gatsby and storybook. Gatsby works without problems, but there are troubles with Storybook. When I run it fails before starting with the following error message:

```
ERROR in ./packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/marduzca/Development/react-google-maps-api/packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  291 | export class InfoWindow extends PureComponent<InfoWindowProps, InfoWindowState> {
  292 |   static contextType = MapContext
> 293 |   declare context: ContextType<typeof MapContext>
      |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I can confirm that this must have come from some of your changes, because it was still working in the branch I had.

**Comment by JustFly1984** [comment]
I've updated typescript to latest 4.7.0 version. 
Can you try to reorder babel plugins in babelOptions, so it comply to error message?
Maybe there is some missing babel plugin.

**Comment by marduzca** [comment]
@JustFly1984 
Sorry but I don't know what you mean. There is nothing called babelOptions anywhere in the repo and there is nothing about babel in main.js
Also there are now many other typescript errors because of unused variables in the MarkerClusterer component
I want to help, but don't know how at the moment

**Comment by JustFly1984** [comment]
@marduzca you can test new components in gatsby-example

babelOptions are in .storybook/main.js webpack config. It is used in tsx/mdx loaders.

**Comment by marduzca** [comment]
@JustFly1984 I can have a look probably tomorrow or on Friday only.
But is all of this necessary? It doesn't actually have relation with the React 18 update, right?
The other commit would be ready for only the update. Can't we just merge that and treat this as a different thing? Because many people are waiting for it apparently

**Comment by JustFly1984** [comment]
@marduzca  I will have time to invest in maintenance release only at weekend.

**Comment by JustFly1984** [comment]
I've released 2.10.0 version. Please test. merging to develop

**Pull request merged**
