### PR TITLE
Export useGoogleMap hook

### PR DESCRIPTION
**Pull request by FredyC**
To be able to access map instance in other components for eg. panning needs.

### CODE REVIEW

**Comment by uriklar** [comment]
@JustFly1984 @FredyC I believe this PR requires us to bump the react version in our peerDependencies right?

**Comment by uriklar** [comment]
image

**Comment by FredyC** [comment]
Well, not necessarily. It's a kinda gray area. As long as people don't use that hook, they are good with older React. That's why is there that invariant, so they don't use it in the wrong environment.

**Comment by uriklar** [comment]
Right you are! Just validated it in a codesandbox to be sure :-)

**Pull request merged**
